### ISSUE TITLE
Add HTTP Status Variable name as a parameter in Rest Task

### ISSUE THREAD

**Issue by Drifftr** [wso2/devstudio-tooling-bps#31]
Currently BPMN Editor plugin's Rest Task element doesn't contain any form field to capture HTTP Status Variable name. But this variable is handled by BPMN core's Rest Task class. We have most of the other related variables as Rest Task properties. So its better to have the support for HTTP Status variable name too.

**Comment by sohaniwso2** [comment]
moved the EI tooling repo at  https://github.com/wso2/devstudio-tooling-ei/issues/188
